@startuml
skinparam style strictuml

participant ClientController
participant TCPServerInterface
participant ServerHandler
participant ClientHandler
participant TCPClientInterface
participant ServerController
participant LobbyController
participant LobbyRunningState
participant CardPickPlayerAction
participant Game
participant RoundActionState

ClientController -> TCPServerInterface: requestAction(LobbyID, CardPickPlayerAction)

activate TCPServerInterface
TCPServerInterface -> ServerHandler: sendMessage(Request)
deactivate TCPServerInterface

activate ServerHandler
ServerHandler -> ClientHandler: PlayerActionRequest()
deactivate ServerHandler

activate ClientHandler
ClientHandler -> TCPClientInterface: handleMessage(Request))
deactivate ClientHandler

activate TCPClientInterface
TCPClientInterface -> ServerController: requestAction(LobbyID, CardPickPlayerAction)
deactivate TCPClientInterface

activate ServerController
ServerController -> LobbyController: playAction(Client, CardPickPlayerAction)
deactivate ServerController

activate LobbyController
LobbyController -> LobbyController: getPlayer(Client)
LobbyController -> CardPickPlayerAction: setPlayer(Player)
LobbyController -> LobbyRunningState: playAction(Client, CardPickPlayerAction)
deactivate LobbyController

activate LobbyRunningState
LobbyRunningState -> CardPickPlayerAction: canExecute(Game)

activate CardPickPlayerAction
CardPickPlayerAction -> Game: getGameState()
CardPickPlayerAction -> RoundActionState: validate()
deactivate CardPickPlayerAction

LobbyRunningState -> CardPickPlayerAction: execute(Game)

activate CardPickPlayerAction
CardPickPlayerAction -> Game: pick(Player, Picks)
deactivate CardPickPlayerAction

activate Game
Game -> LobbyRunningState: notifyOfferResolution(Player, Picks)
deactivate Game

LobbyRunningState -> TCPClientInterface: updateModel(Player, Picks)

activate TCPClientInterface
TCPClientInterface -> ClientHandler: sendMessage(Response)
deactivate TCPClientInterface

activate ClientHandler
ClientHandler -> ServerHandler: OfferResolutionResponse()
deactivate ClientHandler

activate ServerHandler
ServerHandler -> TCPServerInterface: handleMessage(Response))
deactivate ServerHandler

activate TCPServerInterface
TCPServerInterface -> ClientController: updateModel(Player, Picks)
deactivate TCPServerInterface

LobbyRunningState -> TCPClientInterface: updateState(State)
deactivate LobbyRunningState

activate TCPClientInterface
TCPClientInterface -> ClientHandler: sendMessage(Response)
deactivate TCPClientInterface

activate ClientHandler
ClientHandler -> ServerHandler: UpdateStateResponse()
deactivate ClientHandler

activate ServerHandler
ServerHandler -> TCPServerInterface: handleMessage(Response))
deactivate ServerHandler

activate TCPServerInterface
TCPServerInterface -> ClientController: updateState(State)
deactivate TCPServerInterface








@enduml