@startuml
skinparam style strictuml

participant ClientController
participant RMIClientService
participant RMIServerInterface
participant RMIClientInterface
participant RMIServerService
participant ServerController
participant LobbyController
participant LobbyRunningState
participant CardPickPlayerAction
participant Game
participant RoundActionState

ClientController -> RMIServerInterface: requestAction(LobbyID, CardPickPlayerAction)

activate RMIServerInterface
RMIServerInterface -> RMIServerService : requestAction(LobbyID, CardPickPlayerAction)
deactivate RMIServerInterface

activate RMIServerService
RMIServerService -> ServerController : submitCPUTask()
deactivate RMIServerService

activate ServerController
ServerController -> LobbyController: playAction(Client, CardPickPlayerAction)
deactivate ServerController

activate LobbyController
LobbyController -> LobbyController: getPlayer(Client)
LobbyController -> CardPickPlayerAction: setPlayer(Player)
LobbyController -> LobbyRunningState: playAction(Client, CardPickPlayerAction)
deactivate LobbyController

activate LobbyRunningState
LobbyRunningState -> CardPickPlayerAction: canExecute(Game)

activate CardPickPlayerAction
CardPickPlayerAction -> Game: getRoundActionState()
CardPickPlayerAction -> RoundActionState: validate()
deactivate CardPickPlayerAction

LobbyRunningState -> CardPickPlayerAction: execute(Game)

activate CardPickPlayerAction
CardPickPlayerAction -> Game: pick(Player, Picks)
deactivate CardPickPlayerAction

activate Game
Game -> LobbyRunningState: notifyOfferResolution(Player, Picks)
deactivate Game

LobbyRunningState -> RMIClientInterface: updateModel(Player, Picks)

activate RMIClientInterface
RMIClientInterface -> RMIClientService: updateModel(Player, Picks)
deactivate RMIClientInterface

activate RMIClientService
RMIClientService -> ClientController: updateModel(Player, Picks)
deactivate RMIClientService

LobbyRunningState -> RMIClientInterface: updateState(State)
deactivate LobbyRunningState

activate RMIClientInterface
RMIClientInterface -> RMIClientService: updateState(State)
deactivate RMIClientInterface

activate RMIClientService
RMIClientService -> ClientController: updateState(State)
deactivate RMIClientService

@enduml