@startuml
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho

package controller {
    package server {
        class ServerController {
            - [static] instance : ServerController
            - networkServer : NetworkServer
            - waitingLobbies : Map<String, LobbyController>
            - runningLobbies : Map<String, LobbyController>
            - clients: Map<String, VirtualClient>

            + [static] getInstance() : ServerController

            + addClient(client : VirtualClient) : void
            + createLobby(clientID : String, lobbyName : String, playerNum : int, playerName : String, totem: Totem) : void
            + joinLobby(clientID : String, lobbyID : String, playerName : String, totem: Totem) : void
            + leaveLobby(clientID : String, lobbyID : String) : void
            + startLobby(lobbyID : String) : void
            + getWaitingLobbies(clientID : String) : void
            + getLobbyInfo(lobbyID : String, clientID : String) : void
        }

        class LobbyController {
            - id : String
            - name : String
            - model : Game
            - clients : List<VirtualClient>

            + addPlayer(client : VirtualClient, playerName : String, totem: Totem) : void
            + removePlayer(client : VirtualClient) : void
            + setName(name : String) : void
            + setID(id : String) : void
            + getModel() : Game
        }

        package network {
            class ClientHandler {
                - clientInterface : ClientTCPInterface
                - socket : Socket
                - gson : Gson

                + run() : void
                + sendMessage(response : Response) : void
            }

            class ClientTCPInterface {
                - clientHandler : ClientHandler

                + handleMessage(request : Request) : void
                + setWaitingLobbies(clientID : String, lobbies : List<Lobby>)
                + showLobbyInfo(clientID : String, lobby : Lobby)
                + setLobby(clientID : String, lobbyID : String, playerName : String, totem : Totem)

            }

            class NetworkServer {
                - ip : String
                - tcpPort: int
                - rmiPort: int
                - serverSocket : ServerSocket
                - serverController : ServerController

                + run() : void
            }
        }
    }

    package client {
        class ClientController {
            - server : VirtualServer

            + connectRMI(registryName : String, ip : String, rmiPort : int) : void
            + connectTCP(ip : String, tcpPort : int) : void
        }

        package network {
            class ServerTCPInterface {
                - clientController : ClientController
                - serverHandler : NetworkClient

                + addClient(client : VirtualClient) : void
                + createLobby(clientID : String, playerNum : int, playerName : String, totem: Totem) : void
                + joinLobby(clientID : String, lobbyID : String, playerName : String, totem: Totem) : void
                + leaveLobby(clientID : String, lobbyID : String) : void
                + startLobby(lobbyID : String) : void
                + getWaitingLobbies(clientID : String) : void
                + getLobbyInfo(clientID : String, lobbyID : String) : void
            }


            class NetworkClient {
                - serverInterface : ServerTCPInterface
                - socket : Socket
                - gson : Gson

                + run() : void
                + sendMessage(request : Request) : void
                + connect(ip : String, tcpPort : int)
            }
        }
    }

    package common {
        interface VirtualClient {
            - id : String

            + handleMessage(request : Request) : void
            + setWaitingLobbies(String, lobbies : List<Lobby>) : void
            + showLobbyInfo(lobby : Lobby) : void
            + setLobby(String, lobbyID : String, playerName : String, totem : Totem) : void
            + removeFromLobby(lobbyID : String) : void
            + showRank() : void
            + showLeaderboard() : void
        }

        interface VirtualServer {
            + addClient(client : VirtualClient) : void
            + createLobby(clientID : String, lobbyName : String, playerNum : int, playerName : String, totem: Totem) : void
            + joinLobby(clientID : String, lobbyID : String, playerName : String, totem: Totem) : void
            + leaveLobby(clientID : String, lobbyID : String) : void
            + startLobby(lobbyID : String) : void
            + getWaitingLobbies(clientID : String) : void
            + getLobbyInfo(lobbyID : String, clientID : String) : void
            + getRank(lobbyID : String, clientID : String) : void
        }

        package messages {
            package requests {
                abstract class Request {
                    - clientID : String

                    + receive(serverController : ServerController) : void
                }

                class PickCardsRequest {
                    - lobbyID : String
                    - topRowPicks : List<Card>
                    - bottomRowPicks : List<Card>

                    + receive(serverController : ServerController) : void
                }

                class CreateLobbyRequest {
                    - playerName : String
                    - totem: Totem

                    + receive(serverController : ServerController) : void
                }

                class JoinLobbyRequest {
                    - lobbyID : String
                    - playerName : String
                    - totem: Totem

                    + receive(serverController : ServerController) : void
                }

                class LeaveLobbyRequest {
                    - lobbyID : String

                    + receive(serverController : ServerController) : void
                }

                class StartLobbyRequest {
                    - lobbyID : String

                    + receive(serverController : ServerController) : void
                }

                class WaitingLobbyRequest {

                    + receive(serverController : ServerController) : void
                }

                class LobbyInfoRequest {
                    - lobbyID : String

                    + receive(serverController : ServerController) : void
                }

                class GetRankRequest {
                    - lobbyID : String

                    + receive(serverController : ServerController) : void
                }

                class GetLeaderboardRequest {

                    + receive(serverController : ServerController) : void
                }
            }

            package responses {
                abstract class Response {
                    - clientID : String

                    + receive(clientController : ClientController) : void
                }

                class PickCardsResponse {
                    - lobbyID : String
                    - topRowPicks : List<Card>
                    - bottomRowPicks : List<Card>

                    + receive(clientController : ClientController) : void
                }

                class JoinLobbyResponse {
                    - lobbyID : String
                    - playerName : String
                    - totem: Totem
                    + receive(clientController : ClientController) : void
                }

                class LeaveLobbyResponse {
                    - lobbyID : String
                    + receive(clientController : ClientController) : void
                }

                class StartLobbyResponse {
                    - lobbyID : String

                    + receive(clientController : ClientController) : void
                }

                class WaitingLobbyResponse {
                    - lobbies : Map<String, Integer>

                    + receive(clientController : ClientController) : void
                }

                class LobbyInfoResponse {
                    - lobby : Lobby

                    + receive(clientController : ClientController) : void
                }

                class GetRankResponse {
                    - lobbyID : String
                    - ranking : Map<String, Integer>

                    + receive(clientController : ClientController) : void
                }

                class GetLeaderboardResponse {
                    - leaderboard : Leaderboard

                    + receive(clientController : ClientController) : void
                }

                class SetIDResponse {
                    + receive(clientController : ClientController) : void
                }
            }
        }
    }
}

' -----------------------------------
' Associations
' -----------------------------------

VirtualClient <|.. ClientController
VirtualClient <|.. ClientTCPInterface
VirtualServer <|.. ServerController
VirtualServer <|.. ServerTCPInterface

PickCardsRequest -|> Request
CreateLobbyRequest -|> Request
JoinLobbyRequest -|> Request
LeaveLobbyRequest -|> Request
WaitingLobbyRequest -|> Request
LobbyInfoRequest -|> Request
GetRankRequest -|> Request
GetLeaderboardRequest -|> Request

PickCardsResponse -|> Response
JoinLobbyResponse -|> Response
LeaveLobbyResponse -|> Response
WaitingLobbyResponse -|> Response
LobbyInfoResponse -|> Response
GetRankResponse -|> Response
GetLeaderboardResponse -|> Response
SetIDResponse-|> Response

' -----------------------------------
' Layout
' -----------------------------------


@enduml