@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam linetype ortho

package "model" as model {

  together {
    class Game {
      - lobbyState: LobbyRunningState;

      - playerConfig : PlayerConfig
      - gameState : GameState
      - buildingHandler : BuildingHandler

      - players : List<Player>
      - board : Board

      + snapshot() : Game
      + pick(player : Player, topPicks : Set<Integer>, bottomPicks : Set<Integer>): void
      + assignTo(player: Player, offerIndex: int): void
      + build() : void
    }

    class BuildingHandler {
      - lastPlayer: Player
      - lastVisitableCard: VisitableCard
      - lastOrderSlot: OrderSlot
      - lastExtraActionState: lastExtraActionState

      - cardPickBuildings : List<VisitableBuilding>
      - sustenanceBuildings : List<VisitableBuilding>
      - huntBuildings : List<VisitableBuilding>
      - cavePaintingBuildings : List<VisitableBuilding>
      - orderTileBuildings : List<VisitableBuilding>
      - extraActionBuildings : List<VisitableBuilding>
      - gameEndBuildings : List<VisitableBuilding>

      + addCardPickBuilding(building : VisitableBuilding) : void
      + addSustenanceBuilding(building : VisitableBuilding) : void
      + addHuntBuilding(building : VisitableBuilding) : void
      + addCavePaintingBuilding(building : VisitableBuilding) : void
      + addOrderTileBuilding(building : VisitableBuilding) : void
      + addGameEndBuilding(building : VisitableBuilding) : void
      + addExtraActionBuilding(building : VisitableBuilding) : void

      + applyCardPickEffects(visitableCard : VisitableCard, player : Player) : void
      + applySustenanceEffects() : void
      + applyHuntEffects() : void
      + applyCavePaintingEffects() : void
      + applyOrderTileEffects(slot : OrderSlot) : void
      + applyExtraActionEffects(state : ExtraActionState, buildingIndex : int) : void
      + applyGameEndEffects() : void

      + visit(building : BonusPPBuilding): void
      + visit(building : BuilderDoublePPBuilding): void
      + visit(building : CavePaintingBuilding): void
      + visit(building : CharacterBonusBuilding): void
      + visit(building : ExtraActionBuilding): void
      + visit(building : FullSetBuilding): void
      + visit(building : HuntBuilding): void
      + visit(building : InventorPairBuilding): void
      + visit(building : NewFullSetBuilding): void
      + visit(building : OrderTileBuilding): void
      + visit(building : SustenanceDiscountBuilding): void
    }

    package board {
      class Board {
        - game : Game

        - deck : Deck
        - topRow : Row
        - bottomRow : Row
        - orderTile : OrderSlot[]
        - offerTrack : OfferTile[]

        + mediumCopy() : Board
        + deepCopy() : Board
        + orderTileCopy() : OrderSlot[]
        + offerTrackCopy() : OfferTile[]

        + fixReferencesTo(players: List<Player>): void
        + getPickable(picks: Set<Integer>, isTop: boolean): List<Pickable>
      }

      class Deck {
        - charEventCards : Queue<AbstractCard>
        - buildingCards : Queue<AbstractCard>
        - ageBuildingsCount : List<Integer>
        - currentEra : int

        + deepCopy() : Deck

        + drawCards(num : int) : List<AbstractCard>
        + drawBuildingCards() : List<AbstractCard>
        + changeEra() : void
      }

      class OfferTile {
        - type : String
        - assignedPlayer : Player
        - bonusFood : int
        - topRowPickable : int
        - bottomRowPickable : int

        + copy() : OfferTile
        + solveBonusFood() : void
      }

      class OrderSlot {
        - assignedPlayer : Player
        - foodDelta : int

        + copy() : void
        + solveDeltaFood() : void
      }

      class Row {
        - sustenanceEventCards : List<Sustenance>
        - eventCards : List<AbstractEvent>
        - characterCards : List<AbstractCharacter>
        - buildingCards : List<AbstractBuilding>

        + deepCopy() : Row
        + addSustenanceEvent(event: Sustenance): void
        + addEvent(event: AbstractEvent): void
        + addCharacter(character: AbstractCharacter): void
        + addCharacter(building : AbstractBuilding): void
      }
    }

    package card {
          abstract class AbstractCard {
            # ID : int

            # type : String
            # resourceName : String
            # era : int
            # isFinal : boolean

            + AbstractCard(source: AbstractCard)
            + clone() : AbstractCard
            + moveTo(row : Row) : void
            + equals(obj : Object) : boolean
          }

          interface BuildingVisitor {
            + visit(v: OrderTileBuilding);
            + visit(v: CavePaintingBuilding);
            + visit(v: HuntBuilding);
            + visit(v: ExtraActionBuilding);
            + visit(v: BonusPPBuilding);
            + visit(v: CharacterBonusBuilding);
            + visit(v: BuilderDoublePPBuilding);
            + visit(v: FullSetBuilding);
            + visit(v: NewFullSetBuilding);
            + visit(v: InventorPairBuilding);
            + visit(v: SustenanceDiscountBuilding);
          }

          interface Pickable {
            + onPick(player : Player, buildingHandler : BuildingHandler) : void
            + removeFrom(row : Row) : void
          }

          interface VisitableBuilding {
            + accept(v : BuildingVisitor) : void
          }

          package building {
            abstract class AbstractBuilding {
              # owner : Player
              # cost : int
              # pp : int

              + AbstractBuilding(source : AbstractBuilding)
              + onPick(player : Player, buildingHandler : BuildingHandler) : void
              + moveTo(row : Row) : void
              + removeFrom(row : Row) : void
              + register(player: Player, buildingHandler: BuildingHandler) : void
            }

               together{
                class CavePaintingBuilding {
                  - bonusFood : int

                  + CavePaintingBuilding(source : CavePaintingBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                  + accept(v: BuildingVisitor) : void
                }

                class ExtraActionBuilding {
                  + ExtraActionBuilding(source : ExtraActionBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                  + accept(v: BuildingVisitor) : void
                }

                class HuntBuilding {
                  - bonusPP : int
                  - bonusFood : int

                  + HuntBuilding(source : HuntBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                  + accept(v: BuildingVisitor) : void
                }

                class RitualDoubleBonusBuilding {
                  + RitualDoubleBonusBuilding(source : RitualDoubleBonusBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                }

                class RitualNoLossBuilding {
                  + RitualNoLossBuilding(source : RitualNoLossBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                }

                class RitualStarsBuilding {
                  - bonusStars : int

                  + RitualStarsBuilding(source : RitualStarsBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                }
             }

             class OrderTileBuilding {
                  + OrderTileBuilding(source : OrderTileBuilding)
                  + clone() : AbstractCard
                  + register(player: Player, buildingHandler: BuildingHandler) : void
                  + accept(v: BuildingVisitor) : void
                 }

              class InventorPairBuilding {
                 + InventorPairBuilding(source : InventorPairBuilding)
                 + clone() : AbstractCard
                 + register(player: Player, buildingHandler: BuildingHandler) : void
                 + accept(v: BuildingVisitor) : void
              }

              class NewFullSetBuilding {
                - minForSet : int

                + NewFullSetBuilding(source : NewFullSetBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void
              }

              class SustenanceDiscountBuilding {
                - inventorDiscount : int
                - shamanDiscount : int
                - hunterDiscount : int
                - collectorDiscount : int
                - artistDiscount : int
                - builderDiscount : int

                + SustenanceDiscountBuilding(source : SustenanceDiscountBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void

                + visit(i : Inventor) : void
                + visit(s : Shaman) : void
                + visit(h : Hunter) : void
                + visit(c : Collector) : void
                + visit(a : Artist) : void
                + visit(b : Builder) : void
              }

              class BonusPPBuilding {
                - bonusPP : int

                + BonusPPBuilding(source : BonusPPBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void
              }

              class BuilderBonusBuilding {
                + BuilderBonusBuilding(source : BuilderBonusBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void
              }

              class CharacterBonusBuilding {
                - inventorBonusPP : int
                - shamanBonusPP : int
                - hunterBonusPP : int
                - collectorBonusPP : int
                - artistBonusPP : int
                - builderBonusPP : int

                + CharacterBonusBuilding(source : CharacterBonusBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void
              }

              class FullSetBuilding {
                + FullSetBuilding(source : FullSetBuilding)
                + clone() : AbstractCard
                + register(player: Player, buildingHandler: BuildingHandler) : void
                + accept(v: BuildingVisitor) : void
              }
          }

          package character {
            abstract class AbstractCharacter {
              + AbstractCharacter(source : AbstractCharacter)

              + addToTribeOf(p : Player) : void
              + onPick(player : Player, buildingHandler : BuildingHandler) : void
              + moveTo(row : Row) : void
              + removeFrom(row : Row) : void
            }

            class Artist {
              + Artist(source : Artist)

              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }

            class Builder {
              - bonusPP : int
              - buildingDiscount : int

              + Builder(source : Builder)
              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }

            class Collector {
              + Collector(source : Collector)
              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }

            class Hunter {
              - hasIcon : boolean

              + Hunter(source : Hunter)
              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }

            class Inventor {
              - inventorType : InventorType

              + Inventor(source : Inventor)
              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }

            enum InventorType {
              BOATWRIGHT
              FLETCHER
              FISHERMAN
              JEWELER
              HERBORIST
              SHEPHERD
              MANUFACTURER
              MUSICIAN
              TANNER
              BAKER
            }

            class Shaman {
              - stars : int

              + Shaman(source : Shaman)
              + clone() : AbstractCard
              + addToTribeOf(p : Player) : void
            }
          }

          package event {
            abstract class AbstractEvent {
              + AbstractEvent(source : AbstractEvent)

              + onEvent(game : Game) : void
              + moveTo(row : Row) : void
            }

            class CavePainting {
              - bonusPP: int
              - malusPP: int
              - numArtistsBonus : int
              - numArtistsMalus : int

              + CavePainting(source : CavePainting)
              + clone() : AbstractCard
              + onEvent(game : Game) : void
            }

            class Hunt {
              - ppMultiplier : int

              + Hunt(source : Hunt)
              + clone() : AbstractCard
              + onEvent(game : Game) : void
            }

            class ShamanicRitual {
              - bonusPP : int
              - malusPP : int

              + ShamanicRitual(source : ShamanicRitual)
              + clone() : AbstractCard
              + onEvent(game : Game) : void
            }

            class Sustenance {
              - ppMultiplier : int

              + Sustenance(source : Sustenance)
              + clone() : AbstractCard
              + onEvent(game : Game) : void
              + moveTo(row : Row): void
            }
          }
        }

    package gameState {
      abstract class GameState {
        # game : Game
        # buildingHandler : BuildingHandler

        + update() : void
        + validate(action : CardPickPlayerAction): String[]
        + validate(action : OfferPickPlayerAction): String[]
        + getGameState(game : Game)
        + isRoundStart(orderTile: OrderSlot[]): boolean
      }

      together {
          class GameStartState {
            + update() : void
            - assignPlayerToOrderTile() : void
            - distributeCards() : void
          }

          class RoundStartState {
            - currPlayer : Player
            - assignedSlots : int

            + update() : void
            + validate(action : OfferPickPlayerAction): String[]
          }

          class RoundActionState {
            - currPlayer : Player
            - offerTrack : OfferTile[*]
            - solvedOffers : int
            - assignedPlayers : int
            - topRowPickable : int
            - bottomRowPickable : int

            + update() : void
            + computePickable() : void
            + getBuildingsCost(): List<Integer>
            + assignToOrderSlot(offerTile : OfferTile) : void

            + validate(action : CardPickPlayerAction): String[]
            - validatePlayer(player : Player): boolean
            - validatePickCount(top: Set<Integer>, bottom: Set<Integer>) : boolean
            - validateIDList(picks: Set<Integer>, row : Row) : boolean
            - validateFoodCost(top: Set<Integer>, bottom: Set<Integer>) : boolean
          }

          class ExtraActionState {
            - currPlayer : Player
            - solvedExtraActions : int

            + update() : void
            + validate(action : CardPickPlayerAction) : String[]
            - validatePlayer(player: Player): boolean
            - validatePickCount(top: Set<Integer>, bottom: Set<Integer>): boolean
            - validateIDList(picks: Set<Integer>, row : Row): boolean
            - validateFoodCost(top: Set<Integer>)
            - canPick(): boolean

          }

          class RoundEndState {
            - bottom : Row
            - top : Row
            - deck : Deck
            - eraChanged: boolean

            + update() : void
            - resolveEvents() : void
            - setUp() : void
            - redrawCards() : void
            - resolveEraChange(): void
          }

          class GameEndState {
            - bottom : Row
            - top : Row
            - players : List<Player>

            + update() : void
            - resolveEvents() : void
            - assignBonusPP(player : Player) : void
            - setLeaderboard() : void
          }
      }
    }

    package player {
      class Player {
        - name : String
        - totem : Totem
        - tribe : Tribe
        - rank : int

        + shallowCopy() : Player
        + mediumCopy() : Player
        + deepCopy() : Player

        + initTribe(initialFood: int): void
        + updateTribe(tribe: Tribe): void
        + registerBuildings(buildingHandler: BuildingHandler): void

        + compareTo(other : Player) : int
        + equals(obj : Object) : boolean
        + hashCode(): int
      }

      class Tribe {
        - food: int
        - pp: int

        - buildings: List<AbstractBuilding>

        - inventors : Map<InventorType, List<Inventor>>
        - shamans : List<Shaman>
        - builders : List<Builder>
        - collectors : List<Collector>
        - hunters : List<Hunter>
        - artists : List<Artist>

        - stars : int
        - sustenanceDiscount : int
        - noLossRitualMod: boolean
        - doubleRitualMod: boolean

        + shallowCopy(): Tribe
        + deepCopy(): Tribe
        + getMinChar() : int
      }

      enum PlayerConfig {
        TWO
        THREE
        FOUR
        FIVE

        - n : int
        - deckConfigFile : String
        - offerTrackConfigFile : String
        - orderTileConfigFile : String
      }

      enum Totem {
        RED
        BLUE
        WHITE
        BLACK
        YELLOW

        - ansiColor: String
      }
    }


  }
}

' -------------------------
' Inheritance
' -------------------------
AbstractCard <|-- AbstractBuilding
AbstractCard <|-- AbstractCharacter
AbstractCard <|-- AbstractEvent

AbstractBuilding <|-- CavePaintingBuilding
AbstractBuilding <|-- ExtraActionBuilding
AbstractBuilding <|-- HuntBuilding
AbstractBuilding <|-- OrderTileBuilding
AbstractBuilding <|-- RitualDoubleBonusBuilding
AbstractBuilding <|-- RitualNoLossBuilding
AbstractBuilding <|-- RitualStarsBuilding
AbstractBuilding <|- InventorPairBuilding
AbstractBuilding <|-- NewFullSetBuilding
AbstractBuilding <|-- SustenanceDiscountBuilding
AbstractBuilding <|-- BonusPPBuilding
AbstractBuilding <|-- BuilderBonusBuilding
AbstractBuilding <|-- CharacterBonusBuilding
AbstractBuilding <|-- FullSetBuilding

VisitableBuilding <|-- CavePaintingBuilding
VisitableBuilding <|-- ExtraActionBuilding
VisitableBuilding <|-- HuntBuilding
VisitableBuilding <|-- OrderTileBuilding
VisitableBuilding <|- InventorPairBuilding
VisitableBuilding <|-- NewFullSetBuilding
VisitableBuilding <|-- SustenanceDiscountBuilding
VisitableBuilding <|-- BonusPPBuilding
VisitableBuilding <|-- BuilderBonusBuilding
VisitableBuilding <|-- CharacterBonusBuilding
VisitableBuilding <|-- FullSetBuilding

AbstractCharacter <|-- Artist
AbstractCharacter <|-- Builder
AbstractCharacter <|-- Collector
AbstractCharacter <|-- Hunter
AbstractCharacter <|-- Inventor
AbstractCharacter <|-- Shaman

AbstractEvent <|-- CavePainting
AbstractEvent <|-- Hunt
AbstractEvent <|-- ShamanicRitual
AbstractEvent <|-- Sustenance

BuildingVisitor <|-- BuildingHandler
Pickable <|-- AbstractBuilding
Pickable <|-- AbstractCharacter

GameState <|-- GameStartState
GameState <|-- RoundStartState
GameState <|-- RoundActionState
GameState <|-- ExtraActionState
GameState <|-- RoundEndState
GameState <|-- GameEndState

' -------------------------
' Associations
' -------------------------
Game --> Board
Game --> PlayerConfig
Game --> GameState
Game --> Player

Board o- Deck
Board o-- Row
Board o-- OfferTile
Board o-- OrderSlot

Deck o-- AbstractCard
Row o-- AbstractCard
Tribe o-- AbstractCard

Player --> Totem
Player --> Tribe

InventorType <-- Inventor

GameState --> BuildingHandler
AbstractEvent --> Game

' -------------------------
' Hidden links to encourage vertical layout
' -------------------------
Game -[hidden]down-> Board
Game -[hidden]down-> Tribe
Game -[hidden]> GameState
Game -[hidden]down-> BuildingHandler

BuildingHandler -[hidden]down-> BuildingVisitor

GameState -[hidden]down-> GameStartState
GameState -[hidden]down-> RoundEndState
GameState -[hidden]down-> RoundActionState
GameStartState -[hidden]-> RoundActionState
RoundStartState -[hidden]-> ExtraActionState

AbstractCharacter -[hidden]down-> Artist
AbstractCharacter -[hidden]down-> Builder
AbstractCharacter -[hidden]down-> Collector
AbstractCharacter -[hidden]down-> Hunter
AbstractCharacter -[hidden]down-> Inventor
AbstractCharacter -[hidden]down-> Shaman
Hunter -[hidden]down-> Shaman
Artist -[hidden]down-> Builder
Inventor -[hidden]down-> Collector

AbstractEvent -[hidden]-> CavePainting
AbstractEvent -[hidden]-> Hunt
AbstractEvent -[hidden]-> ShamanicRitual
AbstractEvent -[hidden]-> Sustenance
CavePainting -[hidden]-> Hunt
ShamanicRitual -[hidden]-> Sustenance

RitualDoubleBonusBuilding -[hidden]down-> RitualNoLossBuilding
RitualNoLossBuilding -[hidden]down-> RitualStarsBuilding
CavePaintingBuilding -[hidden]down-> HuntBuilding
HuntBuilding -[hidden]down-> ExtraActionBuilding
BonusPPBuilding -[hidden]down-> OrderTileBuilding
OrderTileBuilding -[hidden]down-> NewFullSetBuilding
FullSetBuilding -[hidden]down-> BuilderBonusBuilding
BuilderBonusBuilding -[hidden]down-> CharacterBonusBuilding
SustenanceDiscountBuilding -[hidden]down-> InventorPairBuilding



'AbstractCard -[hidden]down-> AbstractCharacter
'AbstractCard -[hidden]down-> AbstractEvent
'
'Player -[hidden]down> Tribe
'Player -[hidden]down-> PlayerConfig
'Player -[hidden]down-> Totem
'

'
'GameState -[hidden]> Deck
'
'
'
'Row -[hidden]down-> AbstractCard
'ExtraActionState -[hidden]down-> AbstractCard
'GameEndState -[hidden]down-> AbstractCard
'RoundActionState -[hidden]down-> AbstractCard
'PlayerConfig-[hidden]down-> AbstractCard



@enduml
