@startuml
skinparam style strictuml

participant ClientController
participant RMIClientService
participant RMIServerInterface
participant RMIClientInterface
participant RMIServerService
participant ServerController
participant LeaderboardDB
participant LobbyRunningState
participant Game
participant GameEndState

Game -> GameEndState : update()

activate GameEndState
GameEndState -> GameEndState: setLeaderboard()
GameEndState -> LobbyRunningState: notifyGameEnd()
deactivate GameEndState

activate LobbyRunningState
LobbyRunningState -> RMIClientInterface:  updateModel(Players)
deactivate LobbyRunningState

activate RMIClientInterface
RMIClientInterface -> RMIClientService: updateModel(Players)
deactivate RMIClientInterface

activate RMIClientService
RMIClientService -> ClientController: submitCPUTask()
deactivate RMIClientService

...

ClientController -> RMIServerInterface: getLeaderboard(LobbySize)

activate RMIServerInterface
RMIServerInterface -> RMIServerService: getLeaderboard(LobbySize)
deactivate RMIServerInterface

activate RMIServerService
RMIServerService -> ServerController: submitCPUTask()
deactivate RMIServerService

activate ServerController
ServerController -> LeaderboardDB : isAvailable()
ServerController -> LeaderboardDB : getLeaderboard(Client, LobbySize)
deactivate ServerController

activate LeaderboardDB
LeaderboardDB -> LeaderboardDB: executeQuery()
LeaderboardDB -> RMIClientInterface: showLeaderboard(LeaderboardResult)
deactivate LeaderboardDB

activate RMIClientInterface
RMIClientInterface -> RMIClientService: showLeaderboard(LeaderboardResult)
deactivate RMIClientInterface

activate RMIClientService
RMIClientService -> ClientController: submitCPUTask()
deactivate RMIClientService


@enduml